-- Idempotente Drops: Fehler werden dank 'continue-on-error' ignoriert
DROP TABLE recipe_category CASCADE CONSTRAINTS;
DROP TABLE recipe CASCADE CONSTRAINTS;
DROP TABLE category CASCADE CONSTRAINTS;

-- CATEGORY
CREATE TABLE category (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title        VARCHAR2(120)   NOT NULL,
  description  VARCHAR2(1000),
  active       NUMBER(1)       DEFAULT 1 NOT NULL,
  CONSTRAINT ck_category_active CHECK (active IN (0,1)),
  CONSTRAINT uk_category_title  UNIQUE (title)
);

-- RECIPE
CREATE TABLE recipe (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title        VARCHAR2(120)   NOT NULL,
  description  VARCHAR2(2000),
  active       NUMBER(1)       DEFAULT 1 NOT NULL,
  CONSTRAINT ck_recipe_active CHECK (active IN (0,1))
);

-- MANY-TO-MANY
CREATE TABLE recipe_category (
  recipe_id   NUMBER NOT NULL,
  category_id NUMBER NOT NULL,
  CONSTRAINT pk_recipe_category PRIMARY KEY (recipe_id, category_id),
  CONSTRAINT fk_rc_recipe   FOREIGN KEY (recipe_id)   REFERENCES recipe(id)   ON DELETE CASCADE,
  CONSTRAINT fk_rc_category FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE CASCADE
);

-- Indexe
CREATE INDEX idx_recipe_title_upper   ON recipe (UPPER(title));
CREATE INDEX idx_category_title_upper ON category (UPPER(title));
